language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  # Install binary pandoc from Rstudio
  - export PATH="$HOME/pandoc:$PATH"
  - mkdir $HOME/pandoc
  - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.12.3.zip
  - unzip -j pandoc-1.12.3.zip pandoc-1.12.3/linux/debian/x86_64/pandoc
      -d $HOME/pandoc
  - chmod +x $HOME/pandoc/pandoc
  - pandoc --version

  - ./travis-tool.sh r_binary_install Rcpp
  - ./travis-tool.sh r_binary_install rgl
  - ./travis-tool.sh r_binary_install XML
  - ./travis-tool.sh r_binary_install RJSONIO
  - ./travis-tool.sh github_package hadley/dplyr
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh github_package rstudio/shiny
  - ./travis-tool.sh github_package rstudio/rmarkdown
  - ./travis-tool.sh github_package yihui/knitr
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

branches:
  except:
  - /-expt$/

notifications:
  email:
    recipients:
    - hadley@rstudio.com
    - winston@rstudio.com
    on_success: change
    on_failure: change

