language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh r_binary_install Rcpp
  - ./travis-tool.sh r_binary_install rgl
  - ./travis-tool.sh r_binary_install XML
  - ./travis-tool.sh r_binary_install RJSONIO
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

branches:
  except:
  - /-expt$/

notifications:
  email:
    recipients:
    - hadley@rstudio.com
    - winston@rstudio.com
    on_success: change
    on_failure: change

